### ISSUE TITLE
removing rnrs and srfi dependencies

### ISSUE THREAD

**Issue by zzkt** [khafatech/rsc3#4]
Not sure if this port is still active, abandoned,  or gone in a different direction (since 2016) but the package is still available via `raco` so...

If you are interested I've made some changes to reduce dependencies on the unrackety parts of scheme (at https://github.com/zzkt/rsc3/commit/d37f0a2e03cc9e9c5bfc0068d494c21151205fb0) and tested most of the examples in racket (near https://github.com/zzkt/rsc3/tree/main/doc/examples) there are also a few scripts to automate conversion of help files. 

It's more or less working (with some issues around sending or updating ugen graphs) so let me know if you want to discuss patches, merging or general misdirection.

**Comment by khafatech** [comment]
This is great! Sorry for the delay, I barely use github anymore.
I'd love to discuss it and see if we could resolve any remaining issues

**Comment by zzkt** [comment]
No problem with the delay. I'm mostly async anyway.

There are a few issues i've stumbled across with rsc3 but it's working well enough for me so far.  I've been using the example files in [graph](https://github.com/zzkt/rsc3/tree/main/doc/examples/graph) and  [racket](https://github.com/zzkt/rsc3/tree/main/doc/examples/racket) folders to keep track of what works (or not) but haven't made many changes beyond pruning and translating...

Looks like rd is still working on the non-racket [rsc3](https://gitlab.com/rd--/rsc3/-/commits/master) so could be interesting to see what has changed since 2016? and what might make sense to sync?

**Comment by zzkt** [comment]
> Sorry for the delay, I barely use github anymore.

@khafatech and let me know if you prefer another comm mode...

**Comment by khafatech** [comment]
@zzkt yes my email is at m@khafateh.com

Could you make a PR with these changes?

**Comment by zzkt** [comment]
i've added https://github.com/khafatech/rsc3/pull/5

**Comment by zzkt** [comment]
...and added https://github.com/khafatech/rsc3/pull/6
